# Generated by Django 2.2.23 on 2021-05-21 00:31

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('研究', 'research'), ('教育', 'education'), ('その他', 'others')], default='研究', max_length=50)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', markdownx.models.MarkdownxField(blank=True, verbose_name='本文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
