# Generated by Django 2.2.23 on 2021-06-08 12:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=1500, verbose_name='本文'),
        ),
    ]
